version: "3.7"
services:
  minio:
    image: 'bitnami/minio:latest'
    volumes:
      - ./data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio"
